// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/v1/ingest.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestService_Push_FullMethodName       = "/fwdcim.v1.IngestService/Push"
	IngestService_PushStream_FullMethodName = "/fwdcim.v1.IngestService/PushStream"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngestServiceClient interface {
	// Push sends a single packet — used by IDR/EDR for low-rate metrics.
	Push(ctx context.Context, in *TelemetryPacket, opts ...grpc.CallOption) (*PushResponse, error)
	// PushStream streams packets — used for high-throughput interface counters.
	PushStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryPacket, PushResponse], error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) Push(ctx context.Context, in *TelemetryPacket, opts ...grpc.CallOption) (*PushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, IngestService_Push_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) PushStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryPacket, PushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IngestService_ServiceDesc.Streams[0], IngestService_PushStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryPacket, PushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_PushStreamClient = grpc.ClientStreamingClient[TelemetryPacket, PushResponse]

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
type IngestServiceServer interface {
	// Push sends a single packet — used by IDR/EDR for low-rate metrics.
	Push(context.Context, *TelemetryPacket) (*PushResponse, error)
	// PushStream streams packets — used for high-throughput interface counters.
	PushStream(grpc.ClientStreamingServer[TelemetryPacket, PushResponse]) error
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) Push(context.Context, *TelemetryPacket) (*PushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedIngestServiceServer) PushStream(grpc.ClientStreamingServer[TelemetryPacket, PushResponse]) error {
	return status.Error(codes.Unimplemented, "method PushStream not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call panics, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_Push_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).Push(ctx, req.(*TelemetryPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_PushStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IngestServiceServer).PushStream(&grpc.GenericServerStream[TelemetryPacket, PushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IngestService_PushStreamServer = grpc.ClientStreamingServer[TelemetryPacket, PushResponse]

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fwdcim.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _IngestService_Push_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PushStream",
			Handler:       _IngestService_PushStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/ingest.proto",
}
