// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/ingest.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                            // populated on reject
	QueueDepth    uint32                 `protobuf:"varint,3,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"` // DCS ingest queue depth — backpressure signal
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *PushResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PushResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PushResponse) GetQueueDepth() uint32 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

var File_proto_v1_ingest_proto protoreflect.FileDescriptor

const file_proto_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/ingest.proto\x12\tfwdcim.v1\x1a\x18proto/v1/telemetry.proto\"c\n" +
	"\fPushResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1f\n" +
	"\vqueue_depth\x18\x03 \x01(\rR\n" +
	"queueDepth2\x91\x01\n" +
	"\rIngestService\x12;\n" +
	"\x04Push\x12\x1a.fwdcim.v1.TelemetryPacket\x1a\x17.fwdcim.v1.PushResponse\x12C\n" +
	"\n" +
	"PushStream\x12\x1a.fwdcim.v1.TelemetryPacket\x1a\x17.fwdcim.v1.PushResponse(\x01B)Z'github.com/faberwork/fwdcim/proto/v1;v1b\x06proto3"

var (
	file_proto_v1_ingest_proto_rawDescOnce sync.Once
	file_proto_v1_ingest_proto_rawDescData []byte
)

func file_proto_v1_ingest_proto_rawDescGZIP() []byte {
	file_proto_v1_ingest_proto_rawDescOnce.Do(func() {
		file_proto_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_ingest_proto_rawDesc), len(file_proto_v1_ingest_proto_rawDesc)))
	})
	return file_proto_v1_ingest_proto_rawDescData
}

var file_proto_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_ingest_proto_goTypes = []any{
	(*PushResponse)(nil),    // 0: fwdcim.v1.PushResponse
	(*TelemetryPacket)(nil), // 1: fwdcim.v1.TelemetryPacket
}
var file_proto_v1_ingest_proto_depIdxs = []int32{
	1, // 0: fwdcim.v1.IngestService.Push:input_type -> fwdcim.v1.TelemetryPacket
	1, // 1: fwdcim.v1.IngestService.PushStream:input_type -> fwdcim.v1.TelemetryPacket
	0, // 2: fwdcim.v1.IngestService.Push:output_type -> fwdcim.v1.PushResponse
	0, // 3: fwdcim.v1.IngestService.PushStream:output_type -> fwdcim.v1.PushResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_ingest_proto_init() }
func file_proto_v1_ingest_proto_init() {
	if File_proto_v1_ingest_proto != nil {
		return
	}
	file_proto_v1_telemetry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_ingest_proto_rawDesc), len(file_proto_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_ingest_proto_goTypes,
		DependencyIndexes: file_proto_v1_ingest_proto_depIdxs,
		MessageInfos:      file_proto_v1_ingest_proto_msgTypes,
	}.Build()
	File_proto_v1_ingest_proto = out.File
	file_proto_v1_ingest_proto_goTypes = nil
	file_proto_v1_ingest_proto_depIdxs = nil
}
