// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/telemetry.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryPacket is the canonical envelope for every metric, event, log,
// or alarm emitted by IDR or EDR and ingested by DCS.
type TelemetryPacket struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // UUIDv7 — generated at source
	OrgId        string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                      // from reader config
	DatacenterId string                 `protobuf:"bytes,3,opt,name=datacenter_id,json=datacenterId,proto3" json:"datacenter_id,omitempty"` // from reader config
	FloorId      string                 `protobuf:"bytes,4,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`                // from reader config
	NetworkId    string                 `protobuf:"bytes,5,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`          // from reader config
	GroupId      string                 `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                // from reader config
	SourceType   string                 `protobuf:"bytes,7,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`       // "host" | "device"
	SourceId     string                 `protobuf:"bytes,8,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`             // hostname, MAC, serial, mgmt IP
	ReaderId     string                 `protobuf:"bytes,9,opt,name=reader_id,json=readerId,proto3" json:"reader_id,omitempty"`             // "idr-<version>" | "edr-<version>"
	TimestampNs  int64                  `protobuf:"varint,10,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`  // Unix nanoseconds, UTC
	Name         string                 `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty"`                                    // metric/event name  e.g. "sys.cpu_pct"
	Tag          string                 `protobuf:"bytes,12,opt,name=tag,proto3" json:"tag,omitempty"`                                      // secondary key — if_index for IF-MIB, "" otherwise
	Value        float64                `protobuf:"fixed64,13,opt,name=value,proto3" json:"value,omitempty"`
	Meta         map[string]string      `protobuf:"bytes,14,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // if_name, vendor_mib, source (SNMP|gNMI), etc.
	// kind: "metric" | "event" | "trap" | "alarm"
	Kind string `protobuf:"bytes,15,opt,name=kind,proto3" json:"kind,omitempty"`
	// severity (events/traps only): "informational" | "minor" | "major" | "critical"
	Severity      string `protobuf:"bytes,16,opt,name=severity,proto3" json:"severity,omitempty"`
	Signature     []byte `protobuf:"bytes,17,opt,name=signature,proto3" json:"signature,omitempty"` // ed25519 over canonical fields
	Nonce         uint64 `protobuf:"varint,18,opt,name=nonce,proto3" json:"nonce,omitempty"`        // monotonic per source_id — replay protection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryPacket) Reset() {
	*x = TelemetryPacket{}
	mi := &file_proto_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryPacket) ProtoMessage() {}

func (x *TelemetryPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryPacket.ProtoReflect.Descriptor instead.
func (*TelemetryPacket) Descriptor() ([]byte, []int) {
	return file_proto_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryPacket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TelemetryPacket) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TelemetryPacket) GetDatacenterId() string {
	if x != nil {
		return x.DatacenterId
	}
	return ""
}

func (x *TelemetryPacket) GetFloorId() string {
	if x != nil {
		return x.FloorId
	}
	return ""
}

func (x *TelemetryPacket) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *TelemetryPacket) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *TelemetryPacket) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *TelemetryPacket) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *TelemetryPacket) GetReaderId() string {
	if x != nil {
		return x.ReaderId
	}
	return ""
}

func (x *TelemetryPacket) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TelemetryPacket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelemetryPacket) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TelemetryPacket) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryPacket) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TelemetryPacket) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TelemetryPacket) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *TelemetryPacket) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TelemetryPacket) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_proto_v1_telemetry_proto protoreflect.FileDescriptor

const file_proto_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/telemetry.proto\x12\tfwdcim.v1\"\xc3\x04\n" +
	"\x0fTelemetryPacket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12#\n" +
	"\rdatacenter_id\x18\x03 \x01(\tR\fdatacenterId\x12\x19\n" +
	"\bfloor_id\x18\x04 \x01(\tR\afloorId\x12\x1d\n" +
	"\n" +
	"network_id\x18\x05 \x01(\tR\tnetworkId\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x1f\n" +
	"\vsource_type\x18\a \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\b \x01(\tR\bsourceId\x12\x1b\n" +
	"\treader_id\x18\t \x01(\tR\breaderId\x12!\n" +
	"\ftimestamp_ns\x18\n" +
	" \x01(\x03R\vtimestampNs\x12\x12\n" +
	"\x04name\x18\v \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\f \x01(\tR\x03tag\x12\x14\n" +
	"\x05value\x18\r \x01(\x01R\x05value\x128\n" +
	"\x04meta\x18\x0e \x03(\v2$.fwdcim.v1.TelemetryPacket.MetaEntryR\x04meta\x12\x12\n" +
	"\x04kind\x18\x0f \x01(\tR\x04kind\x12\x1a\n" +
	"\bseverity\x18\x10 \x01(\tR\bseverity\x12\x1c\n" +
	"\tsignature\x18\x11 \x01(\fR\tsignature\x12\x14\n" +
	"\x05nonce\x18\x12 \x01(\x04R\x05nonce\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B)Z'github.com/faberwork/fwdcim/proto/v1;v1b\x06proto3"

var (
	file_proto_v1_telemetry_proto_rawDescOnce sync.Once
	file_proto_v1_telemetry_proto_rawDescData []byte
)

func file_proto_v1_telemetry_proto_rawDescGZIP() []byte {
	file_proto_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_telemetry_proto_rawDesc), len(file_proto_v1_telemetry_proto_rawDesc)))
	})
	return file_proto_v1_telemetry_proto_rawDescData
}

var file_proto_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_telemetry_proto_goTypes = []any{
	(*TelemetryPacket)(nil), // 0: fwdcim.v1.TelemetryPacket
	nil,                     // 1: fwdcim.v1.TelemetryPacket.MetaEntry
}
var file_proto_v1_telemetry_proto_depIdxs = []int32{
	1, // 0: fwdcim.v1.TelemetryPacket.meta:type_name -> fwdcim.v1.TelemetryPacket.MetaEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_telemetry_proto_init() }
func file_proto_v1_telemetry_proto_init() {
	if File_proto_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_telemetry_proto_rawDesc), len(file_proto_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_v1_telemetry_proto_msgTypes,
	}.Build()
	File_proto_v1_telemetry_proto = out.File
	file_proto_v1_telemetry_proto_goTypes = nil
	file_proto_v1_telemetry_proto_depIdxs = nil
}
