services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: fwdcim
      POSTGRES_PASSWORD: fwdcim
      POSTGRES_DB: fwdcim
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
